#define 			VAR				1
#define 			CONST			2
#define				INT				3
#define				IF				4
#define				ELSE			5
#define				WHILE			6
#define				PRINT			7
#define				READ			8
#define				ID				9	
#define             INTLITERAL      10
#define 			CHARCHAIN		11
#define				COMMENT1		12
#define				COMMENT2		13
#define             SEMICOLON       14
#define             COMMA         	15
#define             PLUSOP        	16
#define             MINUSOP         17
#define				MULTOP			18
#define				DIVOP			19
#define            	ASSIGNOP       	20
#define             LPAREN          21
#define             RPAREN          22
#define             LKEY	        23
#define             RKEY         	24
#define				INTERROGANT		25
#define 			TWODOTS			26
#define 			ERROR			27
